### ISSUE TITLE
Typo on `insert` operations

### ISSUE THREAD

**Issue by sixclones** [LingDong-/wax#5]
At line 212 it seems that the snippet is not correct.

The doc says:
> To insert `v` into a an array `x` at index `i`, use

But the index `i`  is missing in the snippet.

```scheme
(insert x v)
```

Should it not be?
```scheme
(insert x i v)
```

**Comment by LingDong-** [comment]
Yes, that's a typo. Now fixed bb6cd9e2f9a71700bb2757de9ba14b457bac4fa5. Thanks a lot for pointing out!
