### ISSUE TITLE
Does wax use short-circuit evaluation for boolean expressions?

### ISSUE THREAD

**Issue by JobLeonard** [LingDong-/wax#6]
Hi, this is a cool project, I'm really enjoying reading through it right now.

Quick question regarding this part of the QUICKSTART.MD documentation:

> a && b && c is:
> 
> (&& a b c)
> 
> which the compiler will read as:
> 
> (&& (&& a b) c)

I'm not proficient in all the languages that Wax compiles to, but the ones that I do know would use short-circuit evaluation on this expression - that is, if `a` is false, then expressions `b` and `c` are not evaluated. Does wax also do this to? Or does it always evaluate all expressions? In either case, does it take special care that all compile targets behave as expected? Or does it not make any assumptions about this at all?

https://en.wikipedia.org/wiki/Short-circuit_evaluation

**Comment by LingDong-** [comment]
Hi @JobLeonard,

Yes, wax takes special care that `&&` `||` and `a?b:c` are short-circuited in all targets.

- Most target languages already have circuiting operators, so those are used.
- On targets that does not (currently WebAssembly is the only one), `(set c (&& a b))` is compiled to

```
tmp = a
if (tmp) tmp = b
c = !!tmp
```


Glad you're enjoying the project!

**Comment by JobLeonard** [comment]
Cool, thanks for explaining! :)

Quickly added line to the quickstart doc to mention it there too
